### ISSUE TITLE
Add version info to output assembly

### ISSUE THREAD

**Issue by BinToss** [HaloSPV3/HCE.DRP#20]
## TODO
- [x] ~~enable Windows Manifest generation~~. Resolved in 5cf285d5.
- [ ] check if GitVersion can autofill 'native' assemblies.

- [ ] if GitVersion cannot autofill the version info, we'll need to fill in the pre-compile manifest file with compile-time variables.

--------------------------------

Ideally, we'll re-use our existing GitVersion configuration for version bumps controlled entirely by commit messages.
